package lukesterlee.c4q.nyc.horoscope;

/**
 * Created by Willee on 5/7/15.
 */

// I'm not sure whether putting data in java class is a good idea or not.
public class Data {

    public static final String[] signs = {"Aries", "Taurus", "Gemini", "Cancer", "Leo", "Virgo", "Libra", "Scorpio", "Sagittarius", "Capricorn", "Aquarius", "Pisces"};

    public static final String[] month = {"January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"};

    public static final String[] personality = {
            "Aries personalities are independent. Being the first of the zodiac signs, they venture out and are go-getters, often leading the way. Their upbeat and magnetic personality often entices others to follow their lead because Aries personalities bring excitement into others lives.",
            "Taurus is not the one who ventures out into the unknown and leads the way, Taurus is the one that will follow the leader and strengthen and build upon the discovered, in other words they are the one that will \"dot the I's and cross the T's\". This perseverance is given to them by their stubborn streak. Taurus stubborn streak is what gives their independence. They like to do things their way. They are perfectly fine on being alone, this way things get done they way they want them to be done. Taurus is not a follower, but they are not the brave one either. Taurus is perfectly independent. With their perseverance, they get things done and can do quite well for themselves.",
            "Gemini are extremely independent. They will not be pinned down by anyone or any rules. They need to experience the world on their own. Change and freedom are extremely important to Gemini, they will never let anyone dictate them, they are extremely independent and freedom is essential to their mental well being.",
            "Cancer is the astrology sign that is packed full of contradictions so when it comes to independence, they possibly can or can not be independent. On one side, they have the perseverance and drive to do what needs to be done, they are self-sufficient and do not need to depend on other people for the material and physical things in life. On the other hand, they depend on people for emotional support and encouragement. A Cancer that is not fully self-actualized will need the constant support of others and will not be very independent but the Cancer that is 'evolved' and has properly harnessed their emotional issues will be wildly successful as an independent human being. They crave attention and comfort from other people and they are happiest when they have a small, close knit group of friends or family.",
            "Leo is very independent but they need something to control and someone to admire them and appreciate them. They are fully capable of being greatly successful on their own but they are much happier if they have an audience and a following of people who look up to them. They would prefer not be alone.",
            "Virgo is a very independent zodiac sign. They are fully able to put their intelligence to use and get things done for themselves. It is possible however that their narrow mindedness causes their creativity to suffer and they may lead regular routine lives. They may dwell too much on the past and over complicate things and this may limit their ability to move forward and confuse themselves. In conclusion, Virgos are able to be independent but the less evolved types will have difficult if someone is not there helping them to achieve more and not be so critical of themselves.",
            "Libras like to be around other people, they are all about partnerships and groups. They are happiest when other people are around and when other people are doing their work. They are lazy but like posh surrounding and nice decor. These two extremes could strike a balance and the Libra living on his own could either have a very messy place or a very intricately decorated place. They can be independent, they have the intelligence and the full capability within but would a Libra rather co-exist/depend on others.",
            "Scorpios are fiercely independent. They are able to accomplish anything they put their mind to and they won't give up. They are perfectly suited to being on their own. They are not social butterflies like some other zodiac signs and some actually prefer to live on their own that way there is never any issue of who controls what at home, they like to be in control.",
            "Independence is Sagittarius' principle, they crave adventure and excitement and welcome change with open arms. Sagittarius is the sign of the philosopher and the explorer, they will go as far as road will go and explore every corner thoroughly in their ever eternal search for wisdom. Freedom is so important to Sagittarius that they will actually make decisions based on the amount of freedom that is given by the choice they have made, as a result, sometimes a good opportunity is turned down because of it's high commitment need, but this is their choice so it is a good choice for them.",
            "Capricorns are very independent because they know their capabilities and therefore they rarely trust others to finish details, they like to do it all themselves. Capricorn is the longer of all zodiac signs.",
            "Aquarius personality is very independent, any attempt to hold them down or restrict them will cause them, to flee. They need to be free to be on their own. Independence is not just desired by Aquarius, it is essential to their well being.",
            "Pisces needs a dominant partner of role model in their life or they will very easily fall into a pit of self-pity and self-undoing. When they are independent and inspired by life's events, their creativity comes shining through but they are unable to be on their own for long before they start dreaming in their imaginary world of happy people and happy endings. They need other people to keep them grounded and on the right track."
    };

    public static final String[] dateMan = {
            "An Aries man has a lust for adventure so if you are thinking about having a relationship with an Aries man, be prepared for fast-paced adventure, novelty and excitement. He is always eager to try new things - including relationships. That is not to say that every Aries man will only provide an exciting and short-lived relationship, but this is usually the case. He might stick around if you are the type of woman that enjoys having the man take the lead and basking in his glory. He enjoys challenge so if you are the woman to offer challenges to him - like playing hard to get - he might stick around longer. Remember, this man is all about the thrill of the chase. Do not however, act as if you don't care about him. He needs you to be \"swept off your feet\" by him. Appear innocent- hard-to-get and he will be wrapped around your little finger. Never take advantage of the Aries man because his short temper will turn into a fury of anger and he way leave and never look back.",
            "The Taurus man is very sensible, he is not the man to sweep you off your feet. He is practical and down to earth. He wants a high quality woman, not a woman for one night. He will survey cautiously before he makes his approach. He is very patient when it comes to a relationship. He will survey the situation and make sure the woman has something to offer him, before he offers himself. Taurus man is a romantic man, he will put his woman on a pedestal, protect her and cherish her. Once he has chosen his woman, he will be very generous, loyal and faithful. He is not a boring man, but he is not for the woman who craves adventure and excitement. Taurus man is for the woman who craves stability and comfort, he is an incredible provider and is a very fine choice as a partner for the right woman. He is in it for the long haul so commitment is no problem for this man.",
            "He is a great date - charming, witty, funny, clever, talkative, creative, adventurous, just make sure you can keep up with him! Women are drawn to Gemini men because of their zest for life and their vitality and enthusiasm. You may have competition to if you are trying to win his heart. Do not expect to win him and keep him all to yourself. He is flighty and dictates his own,. He will not allow himself to be pinned down and ruled by a woman. You are going to be his sidekick, not his passionate lover. He loves women and is very good at persuading them and manipulating them with his cleverness getting them into bed, he will say anything to get what he wants. He is the master of seduction. If you are looking for a great fling, the gemini man is your top choice.",
            "The Cancer man will not be direct with you. He will approach you cautiously and slowly. He will be very romantic and flirty and attempt to court you and win your heart with lavish gifts and attention. The reason he will never be direct with you is that he has a strong underlying fear of rejection. Of you are interested in a Cancer man, you will probably have to make the first move and ask him on a date. He falls in love easily and will make you his whole world. Once you \"belong to him\", he will hold on to you and can become quite jealous and possessive. This is because he is worried he will lose you to another man and that would crush his spirit. He needs you to be loyal and faithful for he is the same, in a strong and close relationship, Cancer men are the most loyal of the astrology signs. They make excellent lovers for the tender woman who loves romance and being swept off her feet. Cancer is very affectionate and thrives on holding hands all the time, and constant physical contact as he absorbs the situation and experiences with his feelings. The cancer man is all about feeling. He might not show it however and might portray a calm and cool exterior but underneath, he feels deeply and intensely. Cancer men are easily offended so do not jokingly make fun of them for they will take offense and get hurt, but once again, this will not be known to you. He will simply sulk on his own while he tries to figure out and dissect what you said. Cancer men are excellent male protectors, they are like the knight in shining armor. If you are the kind of woman that likes being looked after and cared for, and loves affection and devotion, this romantic, sensual man is perfect for you.",
            "The Leo man falls in love easily and it usually does not last. This is because his emotional ideals of a grand and magnificent love affair quickly turn into reality. Leo man needs a woman who is grounded and in-tune with the realities of life so she can help him keep his feet on the ground. He may seem like he is casual and detached about love but this is not the case, he needs adoration and approval and if he receives this, he feels quite passionately inside and will treat her with amazing affection and be a wonderful cheerful companion. The Leo man appears to be a rock solid unemotional king but truthfully, he is very sensitive. He wants a woman who caters to him, not in a demanding way but he thinks he is entitled to this because of how great he is. Leo men are prone to be self-centered but underneath they are gentle and have lots of love to give providing the woman can give him what he wants. Leos get along with just about anyone and just about any type of girl is suited to him. The woman who caters to him and overlooks his faults (he thinks he does not have any) and the woman who does not nag at him will obviously have preference and a chance at a long term relationship. If the relationship lasts, eventually she will have to teach him that he is not the only great thing in the world.",
            "The Virgo man has a cool exterior with a sensitive interior. He has tremendous respect for a woman and will treat her like and equal. He likes woman who stir his emotions because he is reluctant to express his own emotions, which he tries and this often causes conflict not just inside himself, but it spills out into the relationship. This man takes patience and understanding. He will not get extremely close so do not try to enter his psyche and become closely entangled, this will make him feel threatened. He needs a classy woman who is not impulsive or unconventional. He leads a predictable life and a predictable woman will make him feel safe. He is perfect for the down to earth, conventional woman. He won't be romantic and sweep you off your feet, but he will be by your side and be very loyal. This man's sensuality comes out with time. For the woman who wants a stable, solid relationship with a visible, smooth sailing future is perfect for the Virgo man.",
            "The Libra man is very popular with women because he is charming, harmonious and can relate to women on their level - a characteristic of Libra is the ability so see the world through the eyes of others. Libra men do this to seduce the girl and it always works. He always seems to be on the search for the perfect women, unfortunately, that does not exist. The closest thing a perfect woman could do is appreciate and be in awe of his stardom. Look up to him, admire him, he is a sucker for flattery. Do not nag or pick on his inability to make a decision, it will simply put pressure on him. You make the decision if he cannot, he will happily go along with you and deep inside will be happy that you took control.",
            "The Scorpio male is unlike any other man of any other astrology sign. He is so unique that a seperate section is needed to explain about dating the Scorpio man. Unlike most other zodiac signs, what it's like to date a Scorpio woman is very similar to dating a Scorpio man. The main difference is that instead of presenting a powerful feminine force like the woman, the Scorpio man presents a strong masculine, sexual force. The Scorpio man is easy to seduce and take home for the night, it is much harder to form a real relationship with him. The Scorpio man is very sensitive and feels lonely and unfulfilled, but he will never let a woman know this. Behind closed doors, be sensitive and affectionate to him appeal to his emotions only if you want a close relationship with him do not attempt to lead him on because he will see this and never forgive you. Toying with a Scorpio male is an unwise move. He will be jealous and possessive and will never allow a woman to control him. Let him take the lead because the Scorpio male is truly a fascinating person, you can never go wrong when he is planning the night! Scorpio men are very moody and their moods change like a pendulum on a clock. Stand by his side in these times and it will pass. Do not nag on him for he has a hard enough time understanding his own emotions. Scorpio men make excellent protectors and you will always feel safe under his radiating, passionate and energetic power.",
            "This man may be difficult to pin down. He loves the trill of the chase so he may be off trying to get other women at the same time you are trying to get him. He is sincere when we says he likes you but he means it to other women when he tells other women the same thing. He is not showy or romantic, and he tends to attract women who like the thrill of the chase themselves, which is not too bad of a gamble. In order to win him over, be modest about love, do not engage him in emotional commitment like conversations about being together in the future. Sagittarius is for the woman who does not want commitment or is afraid of being tied down in a relationship. This man is perfect for the adventurous, fearless female.",
            "The Capricorn man is very physical and passionate, but not emotional (on the outside). Deep inside he yearns for love but this takes a long time to become reality, he is very reluctant to place trust in another person. Show him how much you admire him and earn trust gradually over time. He is very faithful, probably the most faithful of all zodiac signs. Underneath his secretive mysterious nature is a romantic streak with a strong sensual side, this side is completely hidden and once unlocked, you'll be amazed at the transformation this man has undergone! Patience and trust is key with a Capricorn man, he has so much to offer the right woman who will wait for him.",
            "This man is all about intellectual stimulation. You can be the prettiest girl in the world but if you do not stir his mind, he won't bother. Communication is so important to this man. Deep inside he longs for love but this causes him inner trouble because of his inability to understand emotion so an Aquarius man in love often stumbles on his own words, be patient with him and don't hold it against him because deep inside, he is having fun. Beware that an Aquarius man can fall out of love as easily as falling in love. The woman has to be able to adapt to him, he will not change for anybody and demands respect and understanding for the way he is, no matter how eccentric his ideals are. He needs stimulation and a partner to share life's adventures with, not just someone to sit on the couch and watch a movie all the time. Do not press him emotionally or tie him down with demands and obligations because this will cause him to run. Never be jealous, this is a big red flag to him and he will leave right away, the Aquarius man can never be tied down. If you give him all he needs, he will be completely faithful so you should not worry when he is out on his own, give him space and respect his privacy and all will be well. Aquarius man is for the woman who loves a challenge and adventure.",
            "Pisces man is is the ultimate romantic, the sensitive man who feels with a woman. Pisces male is the ideal zodiac sign for the woman who complains that men are not sensitive enough, this man is. However, he has such an ideal of romance that is unrealistic and will fall out of love when he realizes that there is no such thing as the perfect woman. This man lives in the world of dreams and he needs a woman to keep him grounded. He always seems to chose the wrong woman, or a woman he can't have like a married woman that way there is no worry about becoming emotionally attached. He needs a woman who can dominate him, but very subtly. She has to be able to help him steer clear of bad habits and bad thoughts. Pisces man needs sensitivity, generosity and compassion, nurture him and he will nurture you back. A fulfilling emotional relationship for the strong yet sensitive woman."
    };
}
